# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: horizon/store/v1/store_context.proto

require 'google/protobuf'


descriptor_data = "\n$horizon/store/v1/store_context.proto\x12\x10horizon.store.v1\"\xb3\x01\n\x17GetRenderContextRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x15\n\rstorefront_id\x18\x02 \x01(\t\x12\x0e\n\x06locale\x18\x03 \x01(\t\x12\x15\n\rconfiguration\x18\x04 \x01(\t\x12\x0c\n\x04page\x18\x05 \x01(\t\x12\x14\n\x0c\x63urrent_page\x18\x06 \x01(\r\x12\x0f\n\x07\x63\x61rt_id\x18\x07 \x01(\t\x12\x12\n\nrequest_id\x18\x08 \x01(\t\"\xfd\x01\n\x18GetRenderContextResponse\x12\x14\n\x0c\x63ontext_json\x18\x01 \x01(\x0c\x12\x16\n\x0e\x63ontext_sha256\x18\x02 \x01(\t\x12\x19\n\x11snapshot_revision\x18\x03 \x01(\t\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12\x15\n\rstorefront_id\x18\x05 \x01(\t\x12\x0e\n\x06locale\x18\x06 \x01(\t\x12\x15\n\rconfiguration\x18\x07 \x01(\t\x12\x0c\n\x04page\x18\x08 \x01(\t\x12\x14\n\x0c\x63urrent_page\x18\t \x01(\r\x12\x0f\n\x07\x63\x61rt_id\x18\n \x01(\t\x12\x12\n\nrequest_id\x18\x0b \x01(\t2\x80\x01\n\x13StoreContextService\x12i\n\x10GetRenderContext\x12).horizon.store.v1.GetRenderContextRequest\x1a*.horizon.store.v1.GetRenderContextResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Horizon
  module Store
    module V1
      GetRenderContextRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("horizon.store.v1.GetRenderContextRequest").msgclass
      GetRenderContextResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("horizon.store.v1.GetRenderContextResponse").msgclass
    end
  end
end
