# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: horizon/store/v1/store_context.proto for package 'horizon.store.v1'

require 'grpc'
require 'horizon/store/v1/store_context_pb'

module Horizon
  module Store
    module V1
      module StoreContextService
        # Mock data authority. Transport authentication binds the caller to tenant_id
        # before any store, configuration, page or cart lookup occurs.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'horizon.store.v1.StoreContextService'

          rpc :GetRenderContext, ::Horizon::Store::V1::GetRenderContextRequest, ::Horizon::Store::V1::GetRenderContextResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
